"""GitHub PR agent: turns human-approved, verified fixes into a remediation pull request.

Every write goes through the MCP server's gated tools, which only allow `acsr/*` branches and never merge.
"""

import base64
from dataclasses import dataclass
from typing import Any

from backend.services.mcp_client import MCPTools
from backend.services.report import fence, sanitize


@dataclass
class FixSummary:
    finding_id: str
    title: str
    cwe: str | None
    file: str
    line: int | None
    diff: str
    explanation: str
    files: dict[str, str]
    verification: dict[str, Any]


def _checks(v: dict[str, Any]) -> str:
    tests = v.get("tests", {})
    rescan = v.get("rescan", {})
    rows = [
        f"- {'✅' if v.get('build', {}).get('ok') else '❌'} project builds",
        f"- {'✅' if v.get('lint', {}).get('clean') else '❌'} no syntax errors or undefined names",
        (
            f"- ✅ tests pass ({tests.get('counts', {}).get('passed', '?')} passed)"
            if tests.get("passed")
            else "- ⚪ no tests were available"
            if tests.get("skipped")
            else "- ❌ tests failing"
        ),
        f"- {'✅' if rescan.get('original_finding_gone') else '❌'} security rescan no longer reports the issue",
        f"- {'✅' if rescan.get('new_findings') == 0 else '❌'} security rescan reports no new findings",
    ]
    return "\n".join(rows)


def render_pr_body(fixes: list[FixSummary], *, scan_id: str, source_pr: int | None) -> str:
    out = ["## 🛡️ Automated security fixes", "",
           f"Generated by the Agentic Code Security Reviewer for scan `{scan_id}`" + (f" of #{source_pr}." if source_pr else "."),
           "Every fix below was **verified automatically** (build, tests, security rescan) and **approved by a human** before this PR was opened. "
           "**Review before merging. This PR is never merged automatically.**", ""]  # fmt: skip
    for i, f in enumerate(fixes, 1):
        out += [
            f"### {i}. {sanitize(f.title, 140)}",
            f"`{sanitize(f.file, 120)}`"
            + (f":{f.line}" if f.line else "")
            + (f" · {f.cwe}" if f.cwe else ""),
            "",
        ]
        if f.explanation:
            out += [f"**What changed:** {sanitize(f.explanation, 400)}", ""]
        out += ["**Verification**", _checks(f.verification), ""]
        out += [
            "<details><summary>Diff</summary>",
            "",
            fence(f.diff[:6000], "diff"),
            "",
            "</details>",
            "",
        ]
        if f.cwe == "CWE-798":
            out += [
                "> ⚠️ **Rotate this credential.** Removing it from source does not revoke it: it remains valid and visible in git history.",
                "",
            ]
    return "\n".join(out)


async def open_remediation_pr(
    tools: MCPTools, *, repo: str, base_ref: str, from_sha: str, scan_id: str, source_pr: int | None, fixes: list[FixSummary],
) -> str:  # fmt: skip
    """Create branch acsr/fix-<scan>, one commit per fix, and open a PR into `base_ref`. Returns the PR URL."""
    if not fixes:
        raise ValueError("no verified fixes to open a pull request for")
    branch = f"acsr/fix-{scan_id[:8]}"
    await tools.call("create_branch", repo=repo, name=branch, from_sha=from_sha)
    for f in (
        fixes
    ):  # verified fixes were built cumulatively, so later commits already include earlier changes
        for path, content in f.files.items():
            msg = f"fix({f.cwe or 'security'}): {sanitize(f.title, 100)}\n\nVerified by ACSR scan {scan_id}."
            await tools.call(
                "apply_patch",
                repo=repo,
                branch=branch,
                path=path,
                content_b64=base64.b64encode(content.encode()).decode(),
                message=msg,
            )
    title = f"Security fixes: {len(fixes)} verified change(s)" + (
        f" for #{source_pr}" if source_pr else ""
    )
    res = await tools.call(
        "create_pull_request",
        repo=repo,
        head=branch,
        base=base_ref,
        title=title,
        body=render_pr_body(fixes, scan_id=scan_id, source_pr=source_pr),
    )
    return str(res["url"])
