"""remediation files and approval

Revision ID: 7ce8c94796cd
Revises: 2e4aec574380
Create Date: 2026-09-20 20:24:59.242593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7ce8c94796cd'
down_revision: Union[str, Sequence[str], None] = '2e4aec574380'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('remediations', sa.Column('files', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False))
    op.add_column('remediations', sa.Column('finding_id', sa.String(length=64), nullable=True))
    op.add_column('remediations', sa.Column('title', sa.Text(), nullable=False))
    op.add_column('remediations', sa.Column('cwe', sa.String(length=16), nullable=True))
    op.add_column('remediations', sa.Column('file_path', sa.String(length=1024), nullable=True))
    op.add_column('remediations', sa.Column('line', sa.Integer(), nullable=True))
    op.add_column('remediations', sa.Column('approved_by', sa.String(length=128), nullable=True))
    op.add_column('remediations', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('remediations', 'approved_at')
    op.drop_column('remediations', 'approved_by')
    op.drop_column('remediations', 'line')
    op.drop_column('remediations', 'file_path')
    op.drop_column('remediations', 'cwe')
    op.drop_column('remediations', 'title')
    op.drop_column('remediations', 'finding_id')
    op.drop_column('remediations', 'files')
    # ### end Alembic commands ###
